# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.vehiculo import Vehiculo  # noqa: F401,E501
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, vehiculos: List[Vehiculo]=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param vehiculos: The vehiculos of this InlineResponse2001.  # noqa: E501
        :type vehiculos: List[Vehiculo]
        """
        self.swagger_types = {
            'vehiculos': List[Vehiculo]
        }

        self.attribute_map = {
            'vehiculos': 'vehiculos'
        }
        self._vehiculos = vehiculos

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vehiculos(self) -> List[Vehiculo]:
        """Gets the vehiculos of this InlineResponse2001.

        Array de los vehículos de un cliente gestionados por el taller.  # noqa: E501

        :return: The vehiculos of this InlineResponse2001.
        :rtype: List[Vehiculo]
        """
        return self._vehiculos

    @vehiculos.setter
    def vehiculos(self, vehiculos: List[Vehiculo]):
        """Sets the vehiculos of this InlineResponse2001.

        Array de los vehículos de un cliente gestionados por el taller.  # noqa: E501

        :param vehiculos: The vehiculos of this InlineResponse2001.
        :type vehiculos: List[Vehiculo]
        """

        self._vehiculos = vehiculos
